# Exercícios

## 1) Crie uma classe que irá modelar características geométricas de um círculo. Deverá implementar os métodos:
        -> Área 
        -> Perímetro
## Utilize atributos de classe e de instância apropriados. Crie um inicializador e métodos.
$area = \pi*r^2$

$perimetro = 2*\pi*r$

In [14]:
# resposta 1
import numpy as np
class Geometrica:
    def __init__(self, raio):
        self.raio = raio
    def area(self):
        return np.pi * (self.raio ** 2)
    def perimetro(self):
        return 2 * np.pi * self.raio
print(Geometrica(10).area())
print(Geometrica(10).perimetro())

314.1592653589793
62.83185307179586


## 2) Crie uma classe chamada matemática que conterá duas classes: trigonométrica e algébrica. Defina dentro da classe trigonométrica as seguintes funções:
    -> seno
    -> cosseno
    -> tangente
## Defina dentro da classe algébrica as seguintes funções: 
    -> soma
    -> subtração
    -> multiplicação
    -> divisão
## Cada função deverá receber array e retornar array

In [72]:
# resposta 2
import numpy as np
class Matematica(object):
    def __init__(self, array_entrada):
        self.array_entrada = array_entrada
    def getTrigonometrica(self):
        return self.Trigonometrica(self)
    def getAlgebrica(self):
        return self.Algebrica(self)
    
    class Trigonometrica(object):
        def __init__(self, Matematica):
            self.Matematica = Matematica
        def seno(self):
            return np.sin(self.Matematica.array_entrada)
        def cosseno(self):
            return np.cos(self.Matematica.array_entrada)
        def tangente(self):
            return np.tan(self.Matematica.array_entrada)
        
    class Algebrica(object):
        def __init__(self, Matematica):
            self.Matematica = Matematica
        def soma(self):
            for idx, numero_array in enumerate(self.Matematica.array_entrada, start=1):
                resultado = numero_array if idx == 1 else resultado + numero_array
            return resultado
        def subtracao(self):
            for idx, numero_array in enumerate(self.Matematica.array_entrada, start=1):
                resultado = numero_array if idx == 1 else resultado - numero_array
            return resultado
        def multiplicacao(self):
            for idx, numero_array in enumerate(self.Matematica.array_entrada, start=1):
                resultado = numero_array if idx == 1 else resultado * numero_array
            return resultado
        def divisao(self):
            for idx, numero_array in enumerate(self.Matematica.array_entrada, start=1):
                resultado = numero_array if idx == 1 else resultado / numero_array
            return resultado
        
trigonometrica = Matematica([6,8,9]).getTrigonometrica()
print(trigonometrica.seno())
print(trigonometrica.cosseno())
print(trigonometrica.tangente())

algebrica = Matematica([6,8,9]).getAlgebrica()
print(algebrica.soma())
print(algebrica.subtracao())
print(algebrica.multiplicacao())
print(algebrica.divisao())

[-0.2794155   0.98935825  0.41211849]
[ 0.96017029 -0.14550003 -0.91113026]
[-0.29100619 -6.79971146 -0.45231566]
23
-11
432
0.08333333333333333


## 3) Dados 2 arrays, A e B, remova de A todo elemento pertencente a B

In [81]:
# resposta 3
a = [0,1,2,3,4,5,6]
b = [1,3,5]
for elemento in b:
    a.remove(elemento)
print(a)

[0, 2, 4, 6]


## 4) Crie uma função que recebe um array, um inteiro n e um inteiro m e que retorne outro array contendo elementos que estão entre os valores n e m do array recebido pela função. 

In [107]:
# resposta 4
import numpy as np
def my_func(i_array, i_n, i_m):
    return np.where((i_n < i_array) & (i_m > i_array))
print(my_func(np.array([0,1,2,3,4,5,6]), 2, 6))

(array([3, 4, 5], dtype=int64),)


## 5) Escreva uma função que recebe um vetor e um inteiro. Compare cada elemento desse vetor com o número inteiro. Se o elemento do vetor for maior, retorne a diferença entre eles, caso contrário, retorne a soma.

In [109]:
# resposta 5
def my_func(i_vetor, i_inteiro):
    for elemento in i_vetor:
        print(elemento - i_inteiro if elemento > i_inteiro else elemento + i_inteiro)
my_func([2,3,4,5,6], 4)

6
7
8
1
2


## 6) Dada a seguinte matriz:
    -> [ 8,1,7
         4,3,9
         5,2,6]
## escreva uma função que retorne a matriz ordenada por um dos eixos. utilize a função built-in sorted para realizar a ordenação

In [128]:
# resposta 6
import numpy as np
def my_func(i_matriz):
    i_matriz.sort(axis=1)

a = np.array([[8,1,7], [4,3,9], [5,2,6]])
my_func(a)
print(a)

[[1 7 8]
 [3 4 9]
 [2 5 6]]
